import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// layout.tsx
export const metadata: Metadata = {
  title:{
    default: 'Welcome to Next.js',
    template: '%s | next.js',
    absolute: '',

  },
  description: "Generated by create next app",
};

const navigations = [
  {title: 'About', href:'/about'},
  {title: 'products', href:'/products'},
  {title: 'blog', href:'/bog' },
  {title: 'contact', href:'/contact'},

]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
